/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.odysz.hello.gradle.java;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String getPackage() {
        return "io.odysz.hello";
    }

	public int majorVersion() {
		return 1;
	}

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
