import { SMenu, SCard, SHeader, SIcon, SButton } from "@surrealism/index.slint";
import { UseIcons } from "@surrealism/use/index.slint";
import { STip } from "@surrealism/src/tip/index.slint";
import { STag } from "@surrealism/src/tag/index.slint";
import { SAlert } from "@surrealism/src/alert/index.slint";

export component App inherits Window {
    height: 600px;
    width: 800px;

    in-out property <string> window-title: "Hello SurrealismUI!";
    title: window-title;

    private property <int> router-index : 0;

    callback menu-changed(int, string, string);

    out property <length> web_x;
    out property <length> web_y;
    out property <length> web_width;
    out property <length> web_height;

    in-out property <string> webview-status: "Webview not started";

    HorizontalLayout {
      left-wrapper:=Rectangle {
        z: 111;
        height: 100%;
        width: menu.width;
        clip: false;
        menu:=SMenu {
          change(index, data) => {
            debug(index, data);
            router-index = index;
            menu-changed(index, data.id, data.name);
          }
        }
      }
      right-wrapper:=Rectangle {
        z: 100;
        width: parent.width - menu.width;
        background: #2b2b32;
        if (router-index == 0) : index-page := Rectangle {
            height: 100%;
            width: 100%;
            VerticalLayout {
              HorizontalLayout {
                padding: 8px;
                alignment: center;
                Rectangle {
                  height:header.height ;
                  width: parent.width - 16px;
                  header:=SHeader {
                    value: [{label:"SurrealismUI",value:"1"},{label:"menu:Index",value:"2"}];
                  }
                }
              }
              HorizontalLayout {
                padding: 24px;
                alignment: space-around;
                STag {
                  theme: Warning;
                  text: "SurrealismUI V0.5.3";
                }
                STag {
                  theme: Success;
                  text: "MIT License";
                }
                STag {
                  theme: Error;
                  text: "Slint for CMake!";
                }
                STag {
                  theme: Error;
                  text: "Credit to: syf20020816@outlook.com";
                }
              }
              HorizontalLayout {
                alignment: center;
                SCard {
                  card-width: 460px;
                  card-height: 320px;
                  SIcon {
                    height: parent.height;
                    width: parent.width;
                    source: @image-url("imgs/anprism.png");
                  }
                }
              }
              HorizontalLayout {
                padding: 24px;
                alignment: space-around;
                SButton {
                  text: "Try SurrealismUI";
                  clicked => {
                    alert.success("Try SurrealismUI!!! Let's GO!");
                  }
                }

                SButton {
                  show-icon: true;
                  icon: UseIcons.icons.Smiling-face;
                  theme: Primary;
                  text: "Star on Github!";
                }
                STip {
                  text: "GO TO SurrealismUI WIKI?\n Click here!";
                  height: wiki-btn.height;
                  width: wiki-btn.width;
                  position: Bottom;
                  wiki-btn:=SButton {
                    theme: Success;
                    text: "Read Wiki!~~~";
                    clicked => {
                      parent.clicked();
                    }
                  }
                }
              }
            }
        }

        if (router-index == 1) : webview_slot := Rectangle {
          background: #e0e0e0;
          Text { text: "Welcome to Page 2: Tree Explorer View"; }
        }

        if (router-index == 2) : Rectangle {
            background: #b0d0d0;
            Text { text: "Welcome to Page 3: Settings View"; }
        }
      }
    }
    alert:= SAlert {
      result-type: Success;
      text: "Credits to: SurrealismUI, a Slint UI Library for CMake!";
    }
}