import { STree, SButton } from "@surrealism/index.slint"; 
import { TreeData, UseIcons } from "@surrealism/use/index.slint"; 

// If using file-tree.slint, uncomment the following line and comment out the above line.
// import { FileTree, TreeData } from "./file-tree.slint";

// The schema layout that will be compiled directly into standard C++ structs
// export struct TreeItem {
//     icon: image,
//     label: string,
//     extra: string,          // Stores absolute directory paths
//     is_expanded: bool,
//     is_dir: bool,
//     selected: bool,
//     binding_info: string,
// }

export component FilesystemExplorer inherits Rectangle {
    
    callback item_clicked(string, bool);
    callback trigger_sync();

    VerticalLayout {
        spacing: 12px;

        // FileTree {
        //     vertical-stretch: 1;
        //     theme: Dark;
        //     tree-data: root.tree_data;
            
        //     clicked(index, label, extra) => {
        //         root.item_clicked(extra, false); 
        //     }
        // }
        STree {
            vertical-stretch: 1;
            theme: Dark;
            // tree-data: root.tree_data;
            
            clicked(index, label, extra) => {
                root.item_clicked(extra, false); 
            }
        }
        HorizontalLayout {
            alignment: end;
            SButton {
                text: "Synchronize System Records";
                clicked => { root.trigger_sync(); }
            }
        }
    }
}