services:
  web:
   image: wordpress
   links:
    - mysql
   environment:
    - WORDPRESS_DB_PASSWORD=password
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_NAME=my-wpdb
    - WORDPRESS_DB_HOST=localhost
   ports:
    - "127.0.0.1:80:80"

  mysql:
   image: mysql:5.7
   environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=my-wpdb
   ports:
    - "127.0.0.1:3306:3306"
