# network name: wordpress_default
# This should see manage UI at http://localhost :
# docker-compose up -d
services:
  web:
   image: wordpress
   links:
    - mysql
   environment:
    - WORDPRESS_DB_PASSWORD=password
    - WORDPRESS_DB_USER=root
    - WORDPRESS_DB_NAME=my-wpdb
    - WORDPRESS_DB_HOST=mysql
   ports:
    - "127.0.0.1:80:80"

  # connect with mysql docker:
  # docker run --network wordpress_default -it --rm mysql:5.7 mysql -h mysql -uroot -p
  mysql:
   image: mysql:5.7
   environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=my-wpdb
   ports:
    - "127.0.0.1:3306:3306"
