#include <iostream>
#include <filesystem>
#include <vector>
#include "app-window.h" // Automatically generated by the Slint compiler

namespace fs = std::filesystem;

// Helper to refresh Slint's file list from a directory path
void refresh_file_list(auto ui, const fs::path& target_path) {
    std::vector<slint::StandardListViewItem> items;
    
    try {
        for (const auto& entry : fs::directory_iterator(target_path)) {
            std::string prefix = entry.is_directory() ? "📁 " : "📄 ";
            std::string filename = entry.path().filename().string();
            
            slint::StandardListViewItem item;
            item.text = slint::SharedString(prefix + filename);
            items.push_back(item);
        }
    } catch (const std::exception& e) {
        std::cerr << "Error reading directory: " << e.what() << std::endl;
    }

    // Wrap vector into a Slint SharedVector model
    auto model = std::make_shared<slint::VectorModel<slint::StandardListViewItem>>(items);
    
    ui->set_current_path(slint::SharedString(target_path.string()));
    ui->set_current_files(model);
}

int main(int argc, char **argv) {
    auto ui = AppWindow::create();
    
    // Start tracking from a baseline directory
    fs::path current_dir = fs::current_path();
    refresh_file_list(ui, current_dir);

    // Register UI Interaction Callbacks
    ui->on_open_item([ui, &current_dir](slint::SharedString item_name) {
        // Strip out visual icon prefixes ("📁 " or "📄 ")
        std::string name = std::string(item_name).substr(5); 
        fs::path chosen_path = current_dir / name;

        if (fs::is_directory(chosen_path)) {
            current_dir = chosen_path;
            refresh_file_list(ui, current_dir);
        } else {
            std::cout << "Opening file natively: " << chosen_path << std::endl;
            // Native file launcher code could go here (e.g., std::system)
        }
    });

    ui->on_go_up([ui, &current_dir]() {
        if (current_dir.has_parent_path()) {
            current_dir = current_dir.parent_path();
            refresh_file_list(ui, current_dir);
        }
    });

    ui->run();
    return 0;
}